main/base/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/shop/', permanent=True)),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('accounts/', include('django.contrib.auth.urls'), name='login-page'),
    path('registration/', views.registration_page, name='registration-page'),
]

main/shop/urls.py
from django.urls import path, include
from . import views

app_name = 'shop'
urlpatterns = [
    # Профиль
    path('', views.index_page, name='index-page'),
    path('profile/', views.profile_page, name='profile-page'),
    path('profile/edit', views.edit_profile, name='edit-profile-page'),
    # Корзина
    path('cart/', views.view_cart, name='view_cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('products/', views.view_products, name='view_products'),
    
    path('products/<int:product_id>', views.single_product, name='single_product'),
]

main/shop/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    title = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    url_image = models.URLField(max_length=200)
    subcription = models.TextField()


    def __str__(self):
        return f"ID: {self.pk} | {self.title} | {self.price}₽"


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)


    def __str__(self):
        return f"ID: {self.pk} | {self.user}"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)


    def __str__(self):
        return f"ID: {self.pk} | User: {self.cart.user} | Title: {self.product.title} | Price: {self.product.price}₽ | Quantity: {self.quantity}"

main/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Импортируем декоратор login_required
from django.contrib.auth.decorators import login_required
# Импортируем форму для регистрации
from django.contrib.auth.forms import UserCreationForm
# Импортируем функции для авторизации
from django.contrib.auth import authenticate, login

from .models import Product, Cart, CartItem


def index_page(request):
    context = {
        'page_name': 'TealuxE',
    }

    return render(request, 'shop/index_page.html', context)


def registration_page(request):
    context = {'page_name': "Registration Page"}

    if request.method == 'POST':  # Если пришёл POST-запрос
        # Используем форму Django и сразу помещаем в неё данные
        reg_form = UserCreationForm(request.POST)
        if reg_form.is_valid():  # Если с формой всё в порядке
            reg_form.save()  # Делаем запись в БД (сохраняем пользователя)

            # Получаем имя пользователя с формы
            username = reg_form.cleaned_data.get('username')
            password = reg_form.cleaned_data.get(
                'password1')  # Получаем пароль пользователя
            # Получение пользователя
            user = authenticate(username=username, password=password)
            # Войти в пользователя по запросу (для конкретного клиента)
            login(request, user)

            return redirect('/')  # Переходим на домашнюю страницу
    else:  # Если к нам пришёл просто запрос
        reg_form = UserCreationForm()  # Создаём пустую форму

    context['reg_form'] = reg_form  # Добавляем форму в context

    return render(request, 'registration/registration_page.html', context)


@login_required
def profile_page(request):
    return render(request, 'profile/profile_page.html')


@login_required
def edit_profile(request):

    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        # UserProfile(user=request.user, first_name=first_name, last_name=last_name, email=email).save()

        user = request.user
        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        user.save()

        return redirect('shop:profile-page')

    return render(request, 'profile/edit_profile.html')


@login_required
def view_cart(request):
    user_cart_items = CartItem.objects.filter(cart__user=request.user)
    total_price = sum(item.product.price *
                      item.quantity for item in user_cart_items)
    return render(request, 'cart/view_cart.html', {'cart_items': user_cart_items, 'total_price': total_price})


@login_required
def add_to_cart(request, product_id):
    product = Product.objects.get(pk=product_id)
    user_cart = Cart.objects.get_or_create(user=request.user)[0]
    cart_item, created = CartItem.objects.get_or_create(
        cart=user_cart, product=product)
    if not created:
        cart_item.quantity += 1
        cart_item.save()
    return redirect('shop:view_products')


@login_required
def remove_from_cart(request, cart_item_id):
    cart_item = CartItem.objects.get(pk=cart_item_id)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('shop:view_cart')


@login_required
def clear_cart(request):
    try:
        user_cart = Cart.objects.get(user=request.user)
        user_cart.cartitem_set.all().delete()
    except Cart.DoesNotExist:
        pass  # Если корзина не существует, просто продолжаем
    return redirect('shop:view_cart')


def view_products(request):
    products = Product.objects.all()
    return render(request, 'cart/products.html', {'products': products})


def single_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    # Получаем ссылку, по которой пользователь перешел на текущую страницу
    referrer_url = request.META.get('HTTP_REFERER', None)
    return render(request, 'cart/single_product.html', {'product': product, 'referrer_url': referrer_url})

main/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ page_name }}</title>
    {% block links %}
    {% endblock %}
</head>
<body>
    <header class="header">
        {% block header %}
        {% endblock %}
    </header>
    <main class="main">
        {% block main %}
        {% endblock %}
    </main>
    <footer class="footer">
        {% block footer %}
        {% endblock %}
    </footer>
</body>
</html>

main/templates/cart/products.html
{% extends 'base/base.html' %}

{% load static %}

{% block links %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant:ital,wght@0,300..700;1,300..700&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'shop/styles/style.css' %}"/>
<link rel="stylesheet" href="{% static 'shop/styles/products.css' %}"/>
{% endblock %}

{% block header %}
{% include 'shop/main-components/header.html' %}
{% endblock %}

{% block main %}

<div class="container">

    <div class="row">
        <div class="text-center p-5 mb-5">
            <h1>Товары</h1>
        </div>
    </div>

    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 justify-content-center">

        {% if not products %}
        <p class="text-center">Извините, но в данный момент нет доступных товаров :(</p>
        {% endif %}

        {% for product in products  %}
        
        <div class="col my-2 mb-4">
            <a href="{% url 'shop:single_product' product.pk %}">
                <div class="card mx-auto" style="width: 18rem;">
                    <img src="{{ product.url_image }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.title }}</h5>
                        <p class="card-text">{{ product.price }} ₽</p>
                        <a href="{% url 'shop:add_to_cart' product.id %}" class="btn btn-dark mt-3 btn-add-to-cart" onclick="handleAddToCart(event)">Добавить в корзину</a>
                    </div>
                </div>
            </a>
        </div>
        
        {% endfor %}
    </div>
</div>

<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script defer src="{% static 'shop/scripts/main.js' %}"></script>
<script defer src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
{% endblock %}

main/templates/cart/single_product.html
{% extends 'base/base.html' %}
{% load static %}

{% block links %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant:ital,wght@0,300..700;1,300..700&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'shop/styles/single_product.css' %}"/>
{% endblock %}

{% block main %}

<div class="container text-center">
    <h1 class="mt-5 mb-5">{{ product.title }}</h1>
    <img class="img-fluid rounded" src="{{ product.url_image }}" alt="" width="300px", height="300px">
    <p class="pt-3 pb-3 fs-3">Цена: {{ product.price }}</p>
    <p class="text-left fs-3">{{ product.subcription}}</p>
    <div class="p-2 text-center">
        
        <!-- <a class="btn btn-danger m-3" href="{% url 'shop:view_cart' %}">Вернуться назад</a> -->

        {% with products_url='http://127.0.0.1:8000/shop/products/' cart_url='http://127.0.0.1:8000/shop/cart/' %}
        {% if referrer_url == products_url %}
            <a class="btn btn-danger m-3" href="{% url 'shop:view_products' %}">Вернуться назад</a>
        {% elif referrer_url == cart_url %}
            <a class="btn btn-danger m-3" href="{% url 'shop:view_cart' %}">Вернуться назад</a>
        {% else %}
            <a class="btn btn-danger m-3" href="{% url 'shop:view_products' %}">Вернуться назад</a>
        {% endif %}
        {% endwith %}
    
        <button class="btn btn-warning m-3" type="submit">Купить</button>
    </div>
    <hr>
    {{ referrer_url }}
</div>

{% endblock %}

main/templates/cart/view_cart.html
{% extends 'base/base.html' %}
{% load static %}

{% block links %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant:ital,wght@0,300..700;1,300..700&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'shop/styles/style.css' %}"/>
<link rel="stylesheet" href="{% static 'shop/styles/view_cart.css' %}"/>
{% endblock %}

{% comment %} {% block main %}
<h1>Shopping Cart</h1>
<ul>
    {% for item in cart_items %}
        <li>
            {{ item.product.title }} - ${{ item.product.price }} x {{ item.quantity }}
            <a href="{% url 'shop:remove_from_cart' cart_item_id=item.id %}">Remove</a>
        </li>
    {% endfor %}
</ul>
<p>Total Price: ${{ total_price }}</p>
<a href="{% url 'shop:clear_cart' %}">Clear Cart</a>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% endblock %} {% endcomment %}

{% block header %}
{% include 'shop/main-components/header.html' %}
{% endblock %}

{% block main %}
<div class="container">
    <table class="table mt-5 table-bordered table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th>Товар</th>
                <th>Цена</th>
                <th>Количество</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart_items %}
            <tr>
                <td>
                    <a href="{% url 'shop:single_product' item.product.pk %}">{{ item.product.title }}</a>
                </td>
                <td>{{ item.product.price }}</td>
                <td>{{ item.quantity }}</td>
                <td> <a class="btn btn-dark" href="{% url 'shop:remove_from_cart' cart_item_id=item.id %}">Удалить</a> </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="p-2 text-center">
    <p>Сумма: {{ total_price }} ₽</p>
    <a class="btn btn-danger m-3" href="{% url 'shop:clear_cart' %}">Очистить корзину</a>
    <button class="btn btn-warning m-3" type="submit">Купить</button>
</div>

<script src="{% static 'shop/scripts/main.js' %}"></script>
{% endblock %}

main/templates/profile/edit_profile.html
{% extends 'base/base.html' %}
{% load static %}

{% block links %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'shop/styles/profile_page.css' %}">
<link rel="stylesheet" href="{% static 'shop/styles/edit_profile.css' %}">
{% endblock %}

{% block main %}
    <section style="background-color: #eee;">
        <div class="container py-5">
          <div class="row">
            <div class="col">
              <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
                <ol class="breadcrumb mb-0">
                  <li class="breadcrumb-item"><a href="{% url 'shop:index-page' %}">Магазин</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'shop:profile-page' %}">Профиль</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Редактирование профиля</li>
                  <li class="ms-auto"><a href="">

                  <form class="my-form" action="/accounts/logout/" method="POST">
                      {% csrf_token %}
                      <button class="btn btn-outline-primary ms-1 btn-sm" type="submit">Выход из системы</button>
                  </form>

                  </a></li>
                </ol>
              </nav>
            </div>
          </div>
      
          <div class="row">
            <div class="col-lg-4">
              <div class="card mb-4">
                <div class="card-body text-center">
                  <img src="{% static 'shop/images/vksit.jpg' %}" alt="avatar"
                    class="rounded-circle img-fluid" style="width: 150px;">
                  <h5 class="my-3">{{ request.user.first_name }} {{ request.user.last_name }}</h5>
                  <p class="text-muted mb-1">{{ request.user.username }}</p>
                  <p class="text-muted mb-4">Вологда</p>
                  <div class="d-flex justify-content-center mb-2">
                    <a class="btn btn-primary" href="{% url 'shop:view_cart' %}">
                      <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                    </a>
                    <a class="btn btn-outline-primary ms-1" href="{% url 'shop:profile-page' %}">
                      <i class="fa fa-user" aria-hidden="true"></i>
                    </a>
                  </div>
                </div>
              </div>
              <div class="card mb-4 mb-lg-0">
                <div class="card-body p-0">
                  <ul class="list-group list-group-flush rounded-3">
                    <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                      <i class="fab fa-vk fa-lg"></i>
                      <p class="mb-0">@link</p>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                      <i class="fab fa-telegram fa-lg" style="color: #333333;"></i>
                      <p class="mb-0">@link</p>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                      <i class="fab fa-discord fa-lg" style="color: #55acee;"></i>
                      <p class="mb-0">@link</p>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-lg-8">
              <div class="card mb-4">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <p class="mb-0">Настройки</p>
                    </div>
                    <div class="col-sm-9">
                        <form class="form-inline" action="{% url 'shop:edit-profile-page' %}" method="POST">
                            {% csrf_token %}

                            <div class="col-sm-9">
                                <p class="text-muted mb-0">
                                    <label class="pb-1" for="">Имя</label>
                                    <input class="form-control my-input" type="text" name='first_name' placeholder="{{ request.user.first_name|default:"" }}" required>
                                </p>
                            </div>
                            <hr>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">
                                    <label class="pb-1" for="">Фамилия</label>
                                    <input class="form-control my-input" type="text" name='last_name' placeholder="{{ request.user.last_name|default:"" }}" required>
                                </p>
                            </div>
                            <hr>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">
                                    <label class="pb-1" for="">Email</label>
                                    <input class="form-control my-input" type="email" name='email' placeholder="{{ request.user.email|default:"" }}" required>
                                </p>
                            </div>
                            <hr>
                            <button class="btn btn-primary btn-width" type="submit">Применить</button>
                        </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% endblock %}

main/templates/profile/edit_profile_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile</title>
</head>
<body>
    <form action="{% url 'shop:edit-profile-page' %}" method="POST">
        {% csrf_token %}
        <label for="first_name">First name:</label>
        <input type="text" name='first_name' required>
        <label for="last_name">Last name:</label>
        <input type="text" name='last_name' required>
        <label for="email">Email:</label>
        <input type="email" name='email' required>
        <input type="submit">
    </form>
</body>
</html>

main/templates/profile/profile_page.html
{% extends 'base/base.html' %}
{% load static %}

{% block links %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'shop/styles/profile_page.css' %}">
{% endblock %}

{% block main %}
    <section style="background-color: #eee;">
        <div class="container py-5">
          <div class="row">
            <div class="col">
              <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
                <ol class="breadcrumb mb-0">
                  <li class="breadcrumb-item"><a href="{% url 'shop:index-page' %}">Магазин</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Профиль</li>
                  <li class="ms-auto"><a href="">

                  <form class="my-form" action="/accounts/logout/" method="POST">
                      {% csrf_token %}
                      <button class="btn btn-outline-primary ms-1 btn-sm" type="submit">Выход из системы</button>
                  </form>

                  </a></li>
                </ol>
              </nav>
            </div>
          </div>
      
          <div class="row">
            <div class="col-lg-4">
              <div class="card mb-4">
                <div class="card-body text-center">
                  <img src="{% static 'shop/images/vksit.jpg' %}" alt="avatar"
                    class="rounded-circle img-fluid" style="width: 150px;">
                  <h5 class="my-3">{{ request.user.first_name }} {{ request.user.last_name }}</h5>
                  <p class="text-muted mb-1">{{ request.user.username }}</p>
                  <p class="text-muted mb-4">Вологда</p>
                  <div class="d-flex justify-content-center mb-2">

                    <a class="btn btn-primary" href="{% url 'shop:view_cart' %}">
                      <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                    </a>
                    <a class="btn btn-outline-primary ms-1" href="{% url 'shop:edit-profile-page' %}">
                      <i class="fa fa-cog" aria-hidden="true"></i>
                    </a>
                  </div>
                </div>
              </div>
              <div class="card mb-4 mb-lg-0">
                <div class="card-body p-0">
                  <ul class="list-group list-group-flush rounded-3">
                    <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                      <i class="fab fa-vk fa-lg"></i>
                      <p class="mb-0">@link</p>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                      <i class="fab fa-telegram fa-lg" style="color: #333333;"></i>
                      <p class="mb-0">@link</p>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                      <i class="fab fa-discord fa-lg" style="color: #55acee;"></i>
                      <p class="mb-0">@link</p>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-lg-8">
              <div class="card mb-4">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <p class="mb-0">Full Name</p>
                    </div>
                    <div class="col-sm-9">
                      <p class="text-muted mb-0">{{ request.user.first_name|default:"None" }} {{ request.user.last_name|default:"None" }}</p>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <p class="mb-0">Email</p>
                    </div>
                    <div class="col-sm-9">
                      <p class="text-muted mb-0">{{ request.user.email|default:"None" }}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% endblock %}

main/templates/profile/profile_page_old.html
{% extends 'base/base.html' %}
{% load static %}

{% block header %}
<ul>
    <li>
        <form action="/shop/" method="GET">
            <button type="submit">Home</button>
        </form>
    </li>
    <li>
        <form action="/accounts/logout/" method="POST">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>
    </li>
</ul>
{% endblock %}

{% block main %}

<h1>Hello - {{ request.user }}</h1>
<p>First name: {{ request.user.first_name }}</p>
<p>Last name: {{ request.user.last_name }}</p>
<p>Email: {{ request.user.email }}</p>

{% endblock %}

main/templates/shop/index_page.html
{% extends 'base/base.html' %}

{% load static %}

{% block links %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant:ital,wght@0,300..700;1,300..700&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'shop/styles/style.css' %}"/>
{% endblock %}

{% block header %}
{% include 'shop/main-components/header.html' %}
{% endblock %}

{% block main %}
{% include 'shop/main-components/main.html' %}
{% endblock %}

{% block footer %}
{% include 'shop/main-components/footer.html' %}

<script defer src="{% static 'shop/scripts/main.js' %}"></script>
{% endblock %}

main/templates/shop/main-components/header.html
{% load static %}

<div class="container">
    <div class="header__inner">
        <a href="{% url 'shop:index-page' %}" class="logo">
            <img src="{% static 'shop/images/logo.svg' %}" alt="TealuxE">
        </a>
        <nav class="menu">
            <button class="menu__btn">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </button>
            <ul class="menu__list">
                <li class="menu__close">
                    <button class="menu__close-btn">
                        <img src="{% static 'shop/images/close.svg' %}" alt="close">
                    </button>
                </li>
                <li class="menu__item"><a href="{% url 'shop:view_products' %}" class="menu__link">Черный</a></li>
                <li class="menu__item"><a href="{% url 'shop:view_products' %}" class="menu__link">Зеленый</a></li>
                <li class="menu__item"><a href="{% url 'shop:view_products' %}" class="menu__link">Белый</a></li>
                <li class="menu__item"><a href="{% url 'shop:view_products' %}" class="menu__link">Улун</a></li>
                <li class="menu__item"><a href="{% url 'shop:view_products' %}" class="menu__link">Пуэр</a></li>
                <li class="mobile-nav">
                    <ul class="mobile-menu">
                        <li class="mobile-menu__item"><a href="#" class="mobile-menu__link">
                            Свяжитесь с нами
                        </a></li>
                        <li class="mobile-menu__item"><a href="#" class="mobile-menu__link">
                            Наш блог
                        </a></li>
                        <li class="mobile-menu__item"><a href="#" class="mobile-menu__link">
                            Отправка и доставка
                        </a></li>
                    </ul>
                    <ul class="mobile-actions"></ul>
                    <ul class="mobile-actions">
                        <li class="user-actions__item">
                             <a href="{% url 'shop:view_cart' %}" class="mobile-actions__link"><img src="{% static 'shop/images/cart.svg' %}" alt=""></a>       
                        </li>
                        <li class="mobile-actions__item">
                            <a href="{% url 'shop:profile-page' %}" class="mobile-actions__link"><img src="{% static 'shop/images/user.svg' %}" alt=""></a>    
                        </li>
                        <li class="mobile-actions__item">
                            <a href="#" class="mobile-actions__item-search">
                                <img src="{% static 'shop/images/search.svg' %}" alt="search">
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <ul class="user-actions">
            <li class="user-actions__item">
                 <a href="{% url 'shop:view_cart' %}" class="user-actions__link"><img src="{% static 'shop/images/cart.svg' %}" alt=""></a>       
            </li>
            <li class="user-actions__item">
                <a href="{% url 'shop:profile-page' %}" class="user-actions__link"><img src="{% static 'shop/images/user.svg' %}" alt=""></a>    
            </li>
            <li class="user-actions__item user-actions__item-search">
                <a href="#" class="user-actions__item-search">
                    <img src="{% static 'shop/images/search.svg' %}" alt="search">
                </a>
            </li>
        </ul>
    </div>
</div>